package gui.components.frames;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.canvas.Canvas;
import javafx.scene.layout.BorderPane;
import javafx.stage.Stage;
import org.jfree.fx.FXGraphics2D;

import java.awt.*;
import java.awt.geom.Rectangle2D;

/**
 * @author Joëlle de Vries
 * @author Dustin Hendriks (Small fix for the "drawTimePanel". Rewrote the schedule class formulas so everything is plotted correctly, also added color randomizer using hexadecimal value).
 * @since 11-02-2019
 * <p>
 * This class draws a graph and a graph time bar. Useful for plotting a schedule.
 */

class VirtualizedView {
    private static final int pixelHeight = 20 * 13;
    private static final int planWidth = 50;
    private static final int yCorrection = 10;

    /**
     * Draws a time bar on a canvas, and returns it.
     *
     * @return A canvas with a time bar drawing on it.
     */

    static Canvas drawTimePanel() {
        Canvas canvas = new Canvas(65, pixelHeight);
        FXGraphics2D graphics = new FXGraphics2D(canvas.getGraphicsContext2D());
        for (int i = 0; i < 13; i++) {
            graphics.drawLine(50, 20 * i + yCorrection, 40, 20 * i + yCorrection);
            if (i <= 1) {
                graphics.drawString("0" + (i + 8) + " : 00", 0, i * 20 + yCorrection);
            } else {
                graphics.drawString((i + 8) + " : 00", 0, i * 20 + yCorrection);
            }
        }
        return canvas;
    }

    /**
     * The schedule class draws a certain time in pixels (so a plan is being visualized and added)
     *
     * @param minutesBegin Defines the begin time (in minutes) of a plan from 08:00 to 20:00.
     * @param minutesEnd   Defines the end time (in minutes) of a plan from 08:00 to 20:00.
     * @param name         Defines the name of plan (this is a subject, so can be maths or chemistry for example).
     * @return Returns a canvas with a visualized plan (random color, there are little over 16 million colors represented by 0x1000000, a random color is being generated by a double between 0 and 1).
     */

    static Canvas schedule(int minutesBegin, int minutesEnd, String name) {
        Canvas canvas = new Canvas(planWidth, pixelHeight);
        FXGraphics2D graphics = new FXGraphics2D(canvas.getGraphicsContext2D());
        double pixelsPerMinute = (pixelHeight / (13 * 60.));
        int beginPixels = (int) (pixelsPerMinute * minutesBegin);
        int endPixels = (int) (pixelsPerMinute * minutesEnd);
        graphics.setColor(new Color((int) (Math.random() * 0x1000000)));
        Rectangle2D rectangle2D = new Rectangle2D.Double(0, beginPixels + yCorrection, planWidth, endPixels - beginPixels);
        graphics.draw(rectangle2D);
        graphics.fill(rectangle2D);
        graphics.setColor(Color.BLACK);
        graphics.drawString(name, 0, yCorrection);
        return canvas;

    }
}
